version: '2'
services:
  mcve-postgresql:
    image: postgres:14
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=jooq-mcve-kotlin-2
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
